**ANN Exercise:**
Predicting whether a bank customer will stay or leave based on the cusomer information provided by the bank. 

1. Import the pandas, numpy and tensorfow libraries.

In [122]:
import pandas as pd
import numpy as np
import tensorflow as tf

2. Import the dataset and select values for the relevant columns that will be used for the analysis. For the x(independent variables) select from 'CreditScore' column upto the 'EstimatedSalary' colum. For y(dependent variables) select the 'Exited' column.

In [123]:
Data = pd.read_csv('Bank_Churn_Dataset.csv')
x = Data.iloc[:,3:-1].values
y = Data.iloc[:,-1].values

In [124]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [125]:
print(y)

[1 0 1 ... 1 1 0]


3. Data preprocessing.

In [126]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [127]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [128]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [129]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [130]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [131]:
print(x_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [132]:
print(x_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [133]:
print(y_train)

[0 0 0 ... 0 0 1]


In [134]:
print(y_test)

[0 1 0 ... 0 0 0]


In [135]:
from sklearn.preprocessing import StandardScaler
se = StandardScaler()
x_train = se.fit_transform(x_train)
x_test = se.transform(x_test)

In [136]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [137]:
print(x_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


4. Initializing the ANN.

In [138]:
ANN = tf.keras.models.Sequential()

5. Adding the input layer, second layer and finally the outer layer.

In [139]:
ANN.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [140]:
ANN.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [141]:
ANN.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

6. Train the ANN. First, compole then train the ANN.

In [142]:
ANN.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [144]:
ANN.fit(x_train, y_train, batch_size = 32, epochs = 40)

Epoch 1/40
250/250 [==============================] - 1s 3ms/step - loss: 0.3377 - accuracy: 0.8656
Epoch 2/40
250/250 [==============================] - 1s 3ms/step - loss: 0.3381 - accuracy: 0.8648
Epoch 3/40
250/250 [==============================] - 1s 2ms/step - loss: 0.3376 - accuracy: 0.8630
Epoch 4/40
250/250 [==============================] - 1s 3ms/step - loss: 0.3374 - accuracy: 0.8635
Epoch 5/40
250/250 [==============================] - 1s 2ms/step - loss: 0.3376 - accuracy: 0.8633
Epoch 6/40
250/250 [==============================] - 1s 2ms/step - loss: 0.3372 - accuracy: 0.8639
Epoch 7/40
250/250 [==============================] - 1s 2ms/step - loss: 0.3374 - accuracy: 0.8635
Epoch 8/40
250/250 [==============================] - 1s 3ms/step - loss: 0.3375 - accuracy: 0.8644
Epoch 9/40
250/250 [==============================] - 1s 3ms/step - loss: 0.3372 - accuracy: 0.8640
Epoch 10/40
250/250 [==============================] - 1s 3ms/step - loss: 0.3378 - accuracy: 0.8637